# Generated by Django 5.1.7 on 2025-03-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing_hub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='private_key',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
