# Generated by Django 5.1.7 on 2025-03-22 08:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharing_hub', '0004_remove_share_text_remove_share_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Share',
            new_name='Upload',
        ),
    ]
